// Initialize EmailJS
emailjs.init('nOjcxbB9Swb_AmQqu');

// Grab the form element
const form = document.getElementById('form');
const outputDiv = document.getElementById('output');

form.addEventListener('submit', event => {
  event.preventDefault();

  // Fetch and validate inputs
  const nameInput = form.user_name.value.trim();
  const emailInput = form.email.value.trim();
  const weight = parseFloat(form.plasticWeight.value);

  if (!nameInput || !emailInput || isNaN(weight) || weight <= 0) {
    alert('Please fill in all fields with valid information.');
    return;
  }

  // Calculate CO₂ figures
  const virginCO2 = weight * 1.9;
  const pcrCO2    = weight * 0.7;
  const savings   = virginCO2 - pcrCO2;
  const carsOff   = savings / 4600;

  // Render results in the page
  outputDiv.innerHTML = `
     <h3>Hi ${nameInput}, here are your results:</h3>
    <details open>
      <summary><strong>Virgin Plastic Emissions</strong></summary>
      <p> ${virginCO2.toFixed(2)} kg CO₂e</p>
    </details>
    <details open>
      <summary><strong>PCR Plastic Emissions</strong></summary>
      <p>${pcrCO2.toFixed(2)} kg CO₂e</p>
    </details>
    <details open>
      <summary><strong>Estimated Carbon Savings</strong></summary>
      <p>${savings.toFixed(2)} kg CO₂e</p>
    </details>
    <p><strong> Equivalent to removing </strong> ${carsOff.toFixed(2)}<strong> off the road for one year.</strong> </p>
	
	 <div class="branding">
      <span>Generated by: <b><i>thinkpac</i></b></span>
    </div>
  `;
  outputDiv.style.display = 'block';

  // Insert computed values into hidden form fields
  form.virgin_co2.value = virginCO2.toFixed(2);
  form.pcr_co2.value    = pcrCO2.toFixed(2);
  form.savings.value    = savings.toFixed(2);
  form.cars_off.value   = carsOff.toFixed(2);

  // Capture image and place into hidden field
  html2canvas(outputDiv).then(canvas => {
    form.report_image.value = canvas.toDataURL('image/png');

    // Send the form via EmailJS
    form.querySelector('#button').value = 'Sending...';
    emailjs.sendForm('service_s6mj7hb', 'template_ex0h1sh', '#form')
      .then(() => {
        form.querySelector('#button').value = 'Send Email';
        alert('Report emailed successfully!');
      })
      .catch(err => {
        form.querySelector('#button').value = 'Send Email';
        console.error('EmailJS error:', err);
        alert('Failed to send report: ' + (err.text || err));
      });
  });
});
