document.getElementById('genBtn').addEventListener('click', calculateAndGenerateReport);

function calculateAndGenerateReport() {
  const name  = document.getElementById('name').value.trim();
  const email = document.getElementById('email').value.trim();
  const weight = parseFloat(document.getElementById('plasticWeight').value);

  if (!name || !email || isNaN(weight) || weight <= 0) {
    alert("Please fill in all fields with valid information.");
    return;
  }

  const virginCO2   = weight * 1.9;
  const pcrCO2      = weight * 0.7;
  const savings     = virginCO2 - pcrCO2;
  const carsOffRoad = savings / 4600;

  const output = document.getElementById('output');
  output.innerHTML = `
    <h3>Hi ${name}, here are your results:</h3>

    <details open>
      <summary><strong>Virgin Plastic Emissions</strong></summary>
      <p>${virginCO2.toFixed(2)} kg CO₂e</p>
    </details>

    <details open>
      <summary><strong>PCR Plastic Emissions</strong></summary>
      <p>${pcrCO2.toFixed(2)} kg CO₂e</p>
    </details>

    <details open>
      <summary><strong>Estimated Carbon Savings</strong></summary>
      <p>${savings.toFixed(2)} kg CO₂e</p>
    </details>

    <p>🌏 Equivalent to removing <strong>${carsOffRoad.toFixed(2)} cars</strong> off the road for one year.</p>
    <p>📩 Click 'Download' to send the full report to your email: <strong>${email}</strong></p>

    <div class="branding">
      <span>Generated by: <b><i>thinkpac</i></b></span>
    </div>

    <p class="screenshot-hide">
      Want to know more about PCR Plastic Packaging?<br>
      <a href="https://www.thinkpac.com.au" target="_blank">Visit our website</a>
    </p>
  `;
  output.style.display = 'block';

  const btn = document.getElementById('downloadBanner');
  btn.style.display = 'inline-block';
  btn.onclick = () => captureAndEmail(
  output,
  email,
  virginCO2,
  pcrCO2,
  savings,
  carsOffRoad
);
}

function captureAndEmail(
  element,
  recipientEmail,
  virginCO2,
  pcrCO2,
  savings,
  carsOffRoad
) {
  const info = document.querySelector('.screenshot-hide');
  info.style.display = 'none';

  html2canvas(element, {
    scale: 0.8   // render at 80% size
  }).then(canvas => {
    info.style.display = '';

    // trigger download of a small PNG if you still want it
    const link = document.createElement('a');
    link.download = 'carbon_savings_result.png';
    link.href = canvas.toDataURL('image/png');
    link.click();

    // then compress to JPEG under 50 KB
    canvas.toBlob(blob => {
      const reader = new FileReader();
      reader.onloadend = () => {
        // strip off the "data:...;base64," prefix
        const base64data = reader.result.split(',')[1];

        emailjs.send(
          'service_s6mj7hb',
          'template_ex0h1sh',
          {
            to_email:      recipientEmail,
            user_name:     document.getElementById('name').value.trim(),
            virgin_co2:    virginCO2.toFixed(2),
            pcr_co2:       pcrCO2.toFixed(2),
            savings:       savings.toFixed(2),
            cars_off:      carsOffRoad.toFixed(2),
          }
        )
        .then(() => alert('Report emailed successfully!'))
        .catch(err => {
          console.error(err);
          alert('Email send failed.');
        });
      };
      // quality 0.7 gives a good trade-off between size & readability
      reader.readAsDataURL(blob);
    }, 'image/jpeg', 0.7);
  });
}
